GET http://localhost:3010/

###
GET http://localhost:3010/feed

###
POST http://localhost:3010/
Content-Type: application/json

{
    "username": "test",
    "tweet": "test"
}

###
GET http://localhost:3010/tweets/einarlop


###
POST http://localhost:3010/delete/605645ea53d6ed1458fa37a1